# Generated by Django 3.2.8 on 2022-01-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='url_twitter',
            field=models.URLField(null=True),
        ),
    ]
