# Generated by Django 3.2.8 on 2022-01-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220105_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='blogarticles',
            name='tags',
            field=models.ManyToManyField(to='blog.Tags'),
        ),
    ]
