# Generated by Django 4.0 on 2022-01-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_contactmodel_date_created_contactmodel_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
