# Generated by Django 3.2.7 on 2021-10-20 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_adress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Paypal', 'Paypal'), ('MercadoPago', 'MercadoPago')], default='Paypal', max_length=11)),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.adress')),
                ('order_product', models.ManyToManyField(to='Order.OrdenProduct')),
            ],
        ),
    ]
