# Generated by Django 3.0 on 2020-03-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('mensaje', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
