# Generated by Django 2.2.13 on 2021-09-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageBanner',
        ),
    ]
