# Generated by Django 3.1.2 on 2021-09-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_delete_imagebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='banner/')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.store')),
            ],
        ),
    ]
