# Generated by Django 3.1.2 on 2021-09-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_imagebanner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='banner/')),
                ('title', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
