# Generated by Django 3.2.8 on 2022-01-06 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_blogmodel_url_twitter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelTable(
            name='blogmodel',
            table='modelblog',
        ),
        migrations.CreateModel(
            name='BlogArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_post', models.CharField(max_length=100, null=True)),
                ('resume_post', models.TextField(null=True)),
                ('body', models.TextField()),
                ('post_image', models.ImageField(upload_to='image')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField()),
                ('author', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
