# Generated by Django 3.2.8 on 2022-01-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220105_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticles',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
