# Generated by Django 3.2.8 on 2022-01-06 02:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_alter_blogarticles_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticles',
            name='author',
        ),
        migrations.AddField(
            model_name='blogarticles',
            name='author',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
