# Generated by Django 3.2.8 on 2022-01-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220105_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticles',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
