# Generated by Django 3.2.8 on 2022-01-06 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_blogarticles_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticles',
            name='author',
        ),
        migrations.AddField(
            model_name='blogarticles',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
