# Generated by Django 2.2.13 on 2021-08-23 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_modelcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='modelsaludo',
            name='mystack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ModelConect'),
        ),
    ]
