# Generated by Django 2.2.13 on 2021-09-03 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210903_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='Autor',
            new_name='autor',
        ),
    ]
