# Generated by Django 2.2.13 on 2021-09-03 01:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210903_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=200)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('price_promocion', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('start', models.IntegerField(default=0)),
            ],
        ),
    ]
