# Generated by Django 2.2.13 on 2021-09-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210903_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_promocion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
