# Generated by Django 3.2.7 on 2021-10-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0007_auto_20211002_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('slug', models.SlugField()),
                ('price', models.FloatField(default=0)),
                ('price_offer', models.FloatField(default=0)),
                ('description', models.TextField()),
                ('rating', models.CharField(choices=[('START1', 'START1'), ('START2', 'START2'), ('START3', 'START3')], default='START1', max_length=10)),
                ('image', models.ImageField(upload_to='product/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.categorystore')),
            ],
        ),
    ]
