# Generated by Django 3.2.7 on 2021-10-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variaton',
            field=models.CharField(default='', max_length=250),
        ),
    ]
