# Generated by Django 2.2.6 on 2020-07-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('log_version', models.CharField(blank=True, default='', max_length=200)),
                ('file_log', models.FileField(upload_to='log')),
            ],
        ),
    ]
