# Generated by Django 3.2.7 on 2021-10-16 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20211016_1534'),
        ('Orden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduct',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.variation'),
        ),
    ]
