# Generated by Django 3.2.7 on 2021-10-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0002_ordenproduct_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencart',
            name='status_order',
            field=models.BooleanField(default=False),
        ),
    ]
