# Generated by Django 2.2.7 on 2020-05-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcontact',
            name='number_phone',
            field=models.IntegerField(blank=True),
        ),
    ]
