# Generated by Django 2.2.7 on 2020-05-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20200523_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcontact',
            name='number_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
