# Generated by Django 2.2.7 on 2020-05-24 02:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20200523_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcontact',
            name='message',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modelcontact',
            name='number_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
