# Generated by Django 3.0.6 on 2020-06-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_modelblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelblog',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
