# Generated by Django 2.2.6 on 2020-06-22 00:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_modelblog_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('number_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('message', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
