# Generated by Django 2.2.6 on 2020-06-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_modelpago'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField(blank=True, default='')),
                ('file_image', models.FileField(upload_to='images_product')),
            ],
        ),
        migrations.RemoveField(
            model_name='modelblog',
            name='count',
        ),
    ]
